-- AlterTable
ALTER TABLE "public"."SJTest" ADD COLUMN     "CON_100MS_CON_IMPULSE_RATIO_asymm_unit" TEXT,
ADD COLUMN     "CON_100MS_CON_IMPULSE_RATIO_asymm_value" DOUBLE PRECISION,
ADD COLUMN     "CON_100MS_CON_IMPULSE_RATIO_left_unit" TEXT,
ADD COLUMN     "CON_100MS_CON_IMPULSE_RATIO_left_value" DOUBLE PRECISION,
ADD COLUMN     "CON_100MS_CON_IMPULSE_RATIO_right_unit" TEXT,
ADD COLUMN     "CON_100MS_CON_IMPULSE_RATIO_right_value" DOUBLE PRECISION;
