-- AlterTable
ALTER TABLE "public"."SJTest" ADD COLUMN     "CON_P2_CON_P1_IMPULSE_RATIO_left_unit" TEXT,
ADD COLUMN     "CON_P2_CON_P1_IMPULSE_RATIO_left_value" DOUBLE PRECISION,
ADD COLUMN     "CON_P2_CON_P1_IMPULSE_RATIO_right_unit" TEXT,
ADD COLUMN     "CON_P2_CON_P1_IMPULSE_RATIO_right_value" DOUBLE PRECISION;
