-- AlterTable
ALTER TABLE "public"."SJTest" ADD COLUMN     "LANDING_IMPULSE_asymm_unit" TEXT,
ADD COLUMN     "LANDING_IMPULSE_asymm_value" DOUBLE PRECISION,
ADD COLUMN     "LANDING_IMPULSE_left_unit" TEXT,
ADD COLUMN     "LANDING_IMPULSE_left_value" DOUBLE PRECISION,
ADD COLUMN     "LANDING_IMPULSE_right_unit" TEXT,
ADD COLUMN     "LANDING_IMPULSE_right_value" DOUBLE PRECISION;
