-- CreateTable
CREATE TABLE "public"."IMTPTest" (
    "id" SERIAL NOT NULL,
    "athleteId" TEXT NOT NULL,
    "recordedUTC" TIMESTAMP(3) NOT NULL,
    "recordedTimeZone" TEXT NOT NULL,
    "testId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "BASELINE_FORCE_asymm_unit" TEXT,
    "BASELINE_FORCE_asymm_value" DOUBLE PRECISION,
    "BASELINE_FORCE_left_unit" TEXT,
    "BASELINE_FORCE_left_value" DOUBLE PRECISION,
    "BASELINE_FORCE_right_unit" TEXT,
    "BASELINE_FORCE_right_value" DOUBLE PRECISION,
    "BASELINE_FORCE_trial_unit" TEXT,
    "BASELINE_FORCE_trial_value" DOUBLE PRECISION,
    "BW_NET_FORCE_AT_100MS_trial_unit" TEXT,
    "BW_NET_FORCE_AT_100MS_trial_value" DOUBLE PRECISION,
    "BW_NET_FORCE_AT_150MS_trial_unit" TEXT,
    "BW_NET_FORCE_AT_150MS_trial_value" DOUBLE PRECISION,
    "BW_NET_FORCE_AT_200MS_trial_unit" TEXT,
    "BW_NET_FORCE_AT_200MS_trial_value" DOUBLE PRECISION,
    "BW_NET_FORCE_AT_50MS_trial_unit" TEXT,
    "BW_NET_FORCE_AT_50MS_trial_value" DOUBLE PRECISION,
    "BW_NET_FORCE_PEAK_trial_unit" TEXT,
    "BW_NET_FORCE_PEAK_trial_value" DOUBLE PRECISION,
    "FORCE_AT_100MS_asymm_unit" TEXT,
    "FORCE_AT_100MS_asymm_value" DOUBLE PRECISION,
    "FORCE_AT_100MS_left_unit" TEXT,
    "FORCE_AT_100MS_left_value" DOUBLE PRECISION,
    "FORCE_AT_100MS_right_unit" TEXT,
    "FORCE_AT_100MS_right_value" DOUBLE PRECISION,
    "FORCE_AT_100MS_trial_unit" TEXT,
    "FORCE_AT_100MS_trial_value" DOUBLE PRECISION,
    "FORCE_AT_150MS_asymm_unit" TEXT,
    "FORCE_AT_150MS_asymm_value" DOUBLE PRECISION,
    "FORCE_AT_150MS_left_unit" TEXT,
    "FORCE_AT_150MS_left_value" DOUBLE PRECISION,
    "FORCE_AT_150MS_right_unit" TEXT,
    "FORCE_AT_150MS_right_value" DOUBLE PRECISION,
    "FORCE_AT_150MS_trial_unit" TEXT,
    "FORCE_AT_150MS_trial_value" DOUBLE PRECISION,
    "FORCE_AT_200MS_asymm_unit" TEXT,
    "FORCE_AT_200MS_asymm_value" DOUBLE PRECISION,
    "FORCE_AT_200MS_left_unit" TEXT,
    "FORCE_AT_200MS_left_value" DOUBLE PRECISION,
    "FORCE_AT_200MS_right_unit" TEXT,
    "FORCE_AT_200MS_right_value" DOUBLE PRECISION,
    "FORCE_AT_200MS_trial_unit" TEXT,
    "FORCE_AT_200MS_trial_value" DOUBLE PRECISION,
    "FORCE_AT_50MS_asymm_unit" TEXT,
    "FORCE_AT_50MS_asymm_value" DOUBLE PRECISION,
    "FORCE_AT_50MS_left_unit" TEXT,
    "FORCE_AT_50MS_left_value" DOUBLE PRECISION,
    "FORCE_AT_50MS_right_unit" TEXT,
    "FORCE_AT_50MS_right_value" DOUBLE PRECISION,
    "FORCE_AT_50MS_trial_unit" TEXT,
    "FORCE_AT_50MS_trial_value" DOUBLE PRECISION,
    "ISO_ABS_IMPULSE_100_asymm_unit" TEXT,
    "ISO_ABS_IMPULSE_100_asymm_value" DOUBLE PRECISION,
    "ISO_ABS_IMPULSE_100_left_unit" TEXT,
    "ISO_ABS_IMPULSE_100_left_value" DOUBLE PRECISION,
    "ISO_ABS_IMPULSE_100_right_unit" TEXT,
    "ISO_ABS_IMPULSE_100_right_value" DOUBLE PRECISION,
    "ISO_ABS_IMPULSE_100_trial_unit" TEXT,
    "ISO_ABS_IMPULSE_100_trial_value" DOUBLE PRECISION,
    "ISO_ABS_IMPULSE_150_asymm_unit" TEXT,
    "ISO_ABS_IMPULSE_150_asymm_value" DOUBLE PRECISION,
    "ISO_ABS_IMPULSE_150_left_unit" TEXT,
    "ISO_ABS_IMPULSE_150_left_value" DOUBLE PRECISION,
    "ISO_ABS_IMPULSE_150_right_unit" TEXT,
    "ISO_ABS_IMPULSE_150_right_value" DOUBLE PRECISION,
    "ISO_ABS_IMPULSE_150_trial_unit" TEXT,
    "ISO_ABS_IMPULSE_150_trial_value" DOUBLE PRECISION,
    "ISO_ABS_IMPULSE_200_asymm_unit" TEXT,
    "ISO_ABS_IMPULSE_200_asymm_value" DOUBLE PRECISION,
    "ISO_ABS_IMPULSE_200_left_unit" TEXT,
    "ISO_ABS_IMPULSE_200_left_value" DOUBLE PRECISION,
    "ISO_ABS_IMPULSE_200_right_unit" TEXT,
    "ISO_ABS_IMPULSE_200_right_value" DOUBLE PRECISION,
    "ISO_ABS_IMPULSE_200_trial_unit" TEXT,
    "ISO_ABS_IMPULSE_200_trial_value" DOUBLE PRECISION,
    "ISO_ABS_IMPULSE_50_asymm_unit" TEXT,
    "ISO_ABS_IMPULSE_50_asymm_value" DOUBLE PRECISION,
    "ISO_ABS_IMPULSE_50_left_unit" TEXT,
    "ISO_ABS_IMPULSE_50_left_value" DOUBLE PRECISION,
    "ISO_ABS_IMPULSE_50_right_unit" TEXT,
    "ISO_ABS_IMPULSE_50_right_value" DOUBLE PRECISION,
    "ISO_ABS_IMPULSE_50_trial_unit" TEXT,
    "ISO_ABS_IMPULSE_50_trial_value" DOUBLE PRECISION,
    "ISO_ABS_IMPULSE_75_asymm_unit" TEXT,
    "ISO_ABS_IMPULSE_75_asymm_value" DOUBLE PRECISION,
    "ISO_ABS_IMPULSE_75_left_unit" TEXT,
    "ISO_ABS_IMPULSE_75_left_value" DOUBLE PRECISION,
    "ISO_ABS_IMPULSE_75_right_unit" TEXT,
    "ISO_ABS_IMPULSE_75_right_value" DOUBLE PRECISION,
    "ISO_ABS_IMPULSE_75_trial_unit" TEXT,
    "ISO_ABS_IMPULSE_75_trial_value" DOUBLE PRECISION,
    "ISO_BM_REL_FORCE_100_trial_unit" TEXT,
    "ISO_BM_REL_FORCE_100_trial_value" DOUBLE PRECISION,
    "ISO_BM_REL_FORCE_150_trial_unit" TEXT,
    "ISO_BM_REL_FORCE_150_trial_value" DOUBLE PRECISION,
    "ISO_BM_REL_FORCE_200_trial_unit" TEXT,
    "ISO_BM_REL_FORCE_200_trial_value" DOUBLE PRECISION,
    "ISO_BM_REL_FORCE_50_trial_unit" TEXT,
    "ISO_BM_REL_FORCE_50_trial_value" DOUBLE PRECISION,
    "ISO_BM_REL_FORCE_PEAK_trial_unit" TEXT,
    "ISO_BM_REL_FORCE_PEAK_trial_value" DOUBLE PRECISION,
    "ISO_BW_REL_FORCE_PEAK_trial_unit" TEXT,
    "ISO_BW_REL_FORCE_PEAK_trial_value" DOUBLE PRECISION,
    "ISO_NET_IMPULSE_100_trial_unit" TEXT,
    "ISO_NET_IMPULSE_100_trial_value" DOUBLE PRECISION,
    "ISO_NET_IMPULSE_150_trial_unit" TEXT,
    "ISO_NET_IMPULSE_150_trial_value" DOUBLE PRECISION,
    "ISO_NET_IMPULSE_200_trial_unit" TEXT,
    "ISO_NET_IMPULSE_200_trial_value" DOUBLE PRECISION,
    "ISO_NET_IMPULSE_50_trial_unit" TEXT,
    "ISO_NET_IMPULSE_50_trial_value" DOUBLE PRECISION,
    "ISO_NET_IMPULSE_75_trial_unit" TEXT,
    "ISO_NET_IMPULSE_75_trial_value" DOUBLE PRECISION,
    "NET_FORCE_AT_100MS_asymm_unit" TEXT,
    "NET_FORCE_AT_100MS_asymm_value" DOUBLE PRECISION,
    "NET_FORCE_AT_100MS_left_unit" TEXT,
    "NET_FORCE_AT_100MS_left_value" DOUBLE PRECISION,
    "NET_FORCE_AT_100MS_right_unit" TEXT,
    "NET_FORCE_AT_100MS_right_value" DOUBLE PRECISION,
    "NET_FORCE_AT_100MS_trial_unit" TEXT,
    "NET_FORCE_AT_100MS_trial_value" DOUBLE PRECISION,
    "NET_FORCE_AT_150MS_asymm_unit" TEXT,
    "NET_FORCE_AT_150MS_asymm_value" DOUBLE PRECISION,
    "NET_FORCE_AT_150MS_left_unit" TEXT,
    "NET_FORCE_AT_150MS_left_value" DOUBLE PRECISION,
    "NET_FORCE_AT_150MS_right_unit" TEXT,
    "NET_FORCE_AT_150MS_right_value" DOUBLE PRECISION,
    "NET_FORCE_AT_150MS_trial_unit" TEXT,
    "NET_FORCE_AT_150MS_trial_value" DOUBLE PRECISION,
    "NET_FORCE_AT_200MS_asymm_unit" TEXT,
    "NET_FORCE_AT_200MS_asymm_value" DOUBLE PRECISION,
    "NET_FORCE_AT_200MS_left_unit" TEXT,
    "NET_FORCE_AT_200MS_left_value" DOUBLE PRECISION,
    "NET_FORCE_AT_200MS_right_unit" TEXT,
    "NET_FORCE_AT_200MS_right_value" DOUBLE PRECISION,
    "NET_FORCE_AT_200MS_trial_unit" TEXT,
    "NET_FORCE_AT_200MS_trial_value" DOUBLE PRECISION,
    "NET_FORCE_AT_50MS_asymm_unit" TEXT,
    "NET_FORCE_AT_50MS_asymm_value" DOUBLE PRECISION,
    "NET_FORCE_AT_50MS_left_unit" TEXT,
    "NET_FORCE_AT_50MS_left_value" DOUBLE PRECISION,
    "NET_FORCE_AT_50MS_right_unit" TEXT,
    "NET_FORCE_AT_50MS_right_value" DOUBLE PRECISION,
    "NET_FORCE_AT_50MS_trial_unit" TEXT,
    "NET_FORCE_AT_50MS_trial_value" DOUBLE PRECISION,
    "NET_PEAK_VERTICAL_FORCE_asymm_unit" TEXT,
    "NET_PEAK_VERTICAL_FORCE_asymm_value" DOUBLE PRECISION,
    "NET_PEAK_VERTICAL_FORCE_left_unit" TEXT,
    "NET_PEAK_VERTICAL_FORCE_left_value" DOUBLE PRECISION,
    "NET_PEAK_VERTICAL_FORCE_right_unit" TEXT,
    "NET_PEAK_VERTICAL_FORCE_right_value" DOUBLE PRECISION,
    "NET_PEAK_VERTICAL_FORCE_trial_unit" TEXT,
    "NET_PEAK_VERTICAL_FORCE_trial_value" DOUBLE PRECISION,
    "PEAK_VERTICAL_FORCE_asymm_unit" TEXT,
    "PEAK_VERTICAL_FORCE_asymm_value" DOUBLE PRECISION,
    "PEAK_VERTICAL_FORCE_left_unit" TEXT,
    "PEAK_VERTICAL_FORCE_left_value" DOUBLE PRECISION,
    "PEAK_VERTICAL_FORCE_right_unit" TEXT,
    "PEAK_VERTICAL_FORCE_right_value" DOUBLE PRECISION,
    "PEAK_VERTICAL_FORCE_trial_unit" TEXT,
    "PEAK_VERTICAL_FORCE_trial_value" DOUBLE PRECISION,
    "RFD_100_150MS_asymm_unit" TEXT,
    "RFD_100_150MS_asymm_value" DOUBLE PRECISION,
    "RFD_100_150MS_left_unit" TEXT,
    "RFD_100_150MS_left_value" DOUBLE PRECISION,
    "RFD_100_150MS_right_unit" TEXT,
    "RFD_100_150MS_right_value" DOUBLE PRECISION,
    "RFD_100_150MS_trial_unit" TEXT,
    "RFD_100_150MS_trial_value" DOUBLE PRECISION,
    "RFD_100_200MS_asymm_unit" TEXT,
    "RFD_100_200MS_asymm_value" DOUBLE PRECISION,
    "RFD_100_200MS_left_unit" TEXT,
    "RFD_100_200MS_left_value" DOUBLE PRECISION,
    "RFD_100_200MS_right_unit" TEXT,
    "RFD_100_200MS_right_value" DOUBLE PRECISION,
    "RFD_100_200MS_trial_unit" TEXT,
    "RFD_100_200MS_trial_value" DOUBLE PRECISION,
    "RFD_150_200MS_asymm_unit" TEXT,
    "RFD_150_200MS_asymm_value" DOUBLE PRECISION,
    "RFD_150_200MS_left_unit" TEXT,
    "RFD_150_200MS_left_value" DOUBLE PRECISION,
    "RFD_150_200MS_right_unit" TEXT,
    "RFD_150_200MS_right_value" DOUBLE PRECISION,
    "RFD_150_200MS_trial_unit" TEXT,
    "RFD_150_200MS_trial_value" DOUBLE PRECISION,
    "RFD_50_100MS_asymm_unit" TEXT,
    "RFD_50_100MS_asymm_value" DOUBLE PRECISION,
    "RFD_50_100MS_left_unit" TEXT,
    "RFD_50_100MS_left_value" DOUBLE PRECISION,
    "RFD_50_100MS_right_unit" TEXT,
    "RFD_50_100MS_right_value" DOUBLE PRECISION,
    "RFD_50_100MS_trial_unit" TEXT,
    "RFD_50_100MS_trial_value" DOUBLE PRECISION,
    "RFD_AT_100MS_asymm_unit" TEXT,
    "RFD_AT_100MS_asymm_value" DOUBLE PRECISION,
    "RFD_AT_100MS_left_unit" TEXT,
    "RFD_AT_100MS_left_value" DOUBLE PRECISION,
    "RFD_AT_100MS_right_unit" TEXT,
    "RFD_AT_100MS_right_value" DOUBLE PRECISION,
    "RFD_AT_100MS_trial_unit" TEXT,
    "RFD_AT_100MS_trial_value" DOUBLE PRECISION,
    "RFD_AT_150MS_asymm_unit" TEXT,
    "RFD_AT_150MS_asymm_value" DOUBLE PRECISION,
    "RFD_AT_150MS_left_unit" TEXT,
    "RFD_AT_150MS_left_value" DOUBLE PRECISION,
    "RFD_AT_150MS_right_unit" TEXT,
    "RFD_AT_150MS_right_value" DOUBLE PRECISION,
    "RFD_AT_150MS_trial_unit" TEXT,
    "RFD_AT_150MS_trial_value" DOUBLE PRECISION,
    "RFD_AT_200MS_asymm_unit" TEXT,
    "RFD_AT_200MS_asymm_value" DOUBLE PRECISION,
    "RFD_AT_200MS_left_unit" TEXT,
    "RFD_AT_200MS_left_value" DOUBLE PRECISION,
    "RFD_AT_200MS_right_unit" TEXT,
    "RFD_AT_200MS_right_value" DOUBLE PRECISION,
    "RFD_AT_200MS_trial_unit" TEXT,
    "RFD_AT_200MS_trial_value" DOUBLE PRECISION,
    "RFD_AT_250MS_asymm_unit" TEXT,
    "RFD_AT_250MS_asymm_value" DOUBLE PRECISION,
    "RFD_AT_250MS_left_unit" TEXT,
    "RFD_AT_250MS_left_value" DOUBLE PRECISION,
    "RFD_AT_250MS_right_unit" TEXT,
    "RFD_AT_250MS_right_value" DOUBLE PRECISION,
    "RFD_AT_250MS_trial_unit" TEXT,
    "RFD_AT_250MS_trial_value" DOUBLE PRECISION,
    "RFD_AT_30MS_asymm_unit" TEXT,
    "RFD_AT_30MS_asymm_value" DOUBLE PRECISION,
    "RFD_AT_30MS_left_unit" TEXT,
    "RFD_AT_30MS_left_value" DOUBLE PRECISION,
    "RFD_AT_30MS_right_unit" TEXT,
    "RFD_AT_30MS_right_value" DOUBLE PRECISION,
    "RFD_AT_30MS_trial_unit" TEXT,
    "RFD_AT_30MS_trial_value" DOUBLE PRECISION,
    "RFD_AT_50MS_asymm_unit" TEXT,
    "RFD_AT_50MS_asymm_value" DOUBLE PRECISION,
    "RFD_AT_50MS_left_unit" TEXT,
    "RFD_AT_50MS_left_value" DOUBLE PRECISION,
    "RFD_AT_50MS_right_unit" TEXT,
    "RFD_AT_50MS_right_value" DOUBLE PRECISION,
    "RFD_AT_50MS_trial_unit" TEXT,
    "RFD_AT_50MS_trial_value" DOUBLE PRECISION,
    "RFD_AT_75MS_asymm_unit" TEXT,
    "RFD_AT_75MS_asymm_value" DOUBLE PRECISION,
    "RFD_AT_75MS_left_unit" TEXT,
    "RFD_AT_75MS_left_value" DOUBLE PRECISION,
    "RFD_AT_75MS_right_unit" TEXT,
    "RFD_AT_75MS_right_value" DOUBLE PRECISION,
    "RFD_AT_75MS_trial_unit" TEXT,
    "RFD_AT_75MS_trial_value" DOUBLE PRECISION,
    "START_OF_MOVEMENT_asymm_unit" TEXT,
    "START_OF_MOVEMENT_asymm_value" DOUBLE PRECISION,
    "START_OF_MOVEMENT_left_unit" TEXT,
    "START_OF_MOVEMENT_left_value" DOUBLE PRECISION,
    "START_OF_MOVEMENT_right_unit" TEXT,
    "START_OF_MOVEMENT_right_value" DOUBLE PRECISION,
    "START_OF_MOVEMENT_trial_unit" TEXT,
    "START_OF_MOVEMENT_trial_value" DOUBLE PRECISION,
    "START_TO_80PC_PEAK_FORCE_asymm_unit" TEXT,
    "START_TO_80PC_PEAK_FORCE_asymm_value" DOUBLE PRECISION,
    "START_TO_80PC_PEAK_FORCE_left_unit" TEXT,
    "START_TO_80PC_PEAK_FORCE_left_value" DOUBLE PRECISION,
    "START_TO_80PC_PEAK_FORCE_right_unit" TEXT,
    "START_TO_80PC_PEAK_FORCE_right_value" DOUBLE PRECISION,
    "START_TO_80PC_PEAK_FORCE_trial_unit" TEXT,
    "START_TO_80PC_PEAK_FORCE_trial_value" DOUBLE PRECISION,
    "START_TO_PEAK_FORCE_asymm_unit" TEXT,
    "START_TO_PEAK_FORCE_asymm_value" DOUBLE PRECISION,
    "START_TO_PEAK_FORCE_left_unit" TEXT,
    "START_TO_PEAK_FORCE_left_value" DOUBLE PRECISION,
    "START_TO_PEAK_FORCE_right_unit" TEXT,
    "START_TO_PEAK_FORCE_right_value" DOUBLE PRECISION,
    "START_TO_PEAK_FORCE_trial_unit" TEXT,
    "START_TO_PEAK_FORCE_trial_value" DOUBLE PRECISION,

    CONSTRAINT "IMTPTest_pkey" PRIMARY KEY ("id")
);
