-- CreateTable
CREATE TABLE "public"."HpObp" (
    "id" SERIAL NOT NULL,
    "test_date" TIMESTAMP(3),
    "playing_level" TEXT,
    "bat_speed_mph_group" TEXT,
    "pitch_speed_mph_group" TEXT,
    "jump_height_(imp-mom)_[cm]_mean_cmj" DOUBLE PRECISION,
    "lower-limb_stiffness_[n/m]_mean_cmj" DOUBLE PRECISION,
    "peak_power_[w]_mean_cmj" DOUBLE PRECISION,
    "peak_power_/_bm_[w/kg]_mean_cmj" DOUBLE PRECISION,
    "eccentric_braking_rfd_[n/s]_mean_cmj" DOUBLE PRECISION,
    "eccentric_duration_[ms]_mean_cmj" DOUBLE PRECISION,
    "concentric_duration_[ms]_mean_cmj" DOUBLE PRECISION,
    "rsi-modified_[m/s]_mean_cmj" DOUBLE PRECISION,
    "countermovement_depth_[cm]_mean_cmj" DOUBLE PRECISION,
    "cmj_stiffness_asymmetry_[%_l,r]_mean_cmj" DOUBLE PRECISION,
    "eccentric_deceleration_impulse_(asymmetry)_[%_l,r]_mean_cmj" DOUBLE PRECISION,
    "p1_concentric_impulse_asymmetry_[%_l,r]_mean_cmj" DOUBLE PRECISION,
    "p2_concentric_impulse_asymmetry_[%_l,r]_mean_cmj" DOUBLE PRECISION,
    "concentric_peak_force_[n]_mean_cmj" DOUBLE PRECISION,
    "eccentric_peak_force_[n]_mean_cmj" DOUBLE PRECISION,
    "minimum_eccentric_force_[n]_mean_cmj" DOUBLE PRECISION,
    "jump_height_(imp-mom)_[cm]_mean_sj" DOUBLE PRECISION,
    "peak_power_[w]_mean_sj" DOUBLE PRECISION,
    "peak_power_/_bm_[w/kg]_mean_sj" DOUBLE PRECISION,
    "p1_concentric_impulse_asymmetry_[%_l,r]_mean_sj" DOUBLE PRECISION,
    "p2_concentric_impulse_asymmetry_[%_l,r]_mean_sj" DOUBLE PRECISION,
    "peak_vertical_force_[n]_max_imtp" DOUBLE PRECISION,
    "net_peak_vertical_force_[n]_max_imtp" DOUBLE PRECISION,
    "force_at_100ms_[n]_max_imtp" DOUBLE PRECISION,
    "force_at_150ms_[n]_max_imtp" DOUBLE PRECISION,
    "force_at_200ms_[n]_max_imtp" DOUBLE PRECISION,
    "best_active_stiffness_[n/m]_mean_ht" DOUBLE PRECISION,
    "best_jump_height_(flight_time)_[cm]_mean_ht" DOUBLE PRECISION,
    "best_rsi_(flight/contact_time)_mean_ht" DOUBLE PRECISION,
    "best_rsi_(jump_height/contact_time)_[m/s]_mean_ht" DOUBLE PRECISION,
    "peak_takeoff_force_[n]_mean_pp" DOUBLE PRECISION,
    "peak_eccentric_force_[n]_mean_pp" DOUBLE PRECISION,
    "peak_takeoff_force_asymmetry_[%_l,r]_mean_pp" DOUBLE PRECISION,
    "peak_eccentric_force_asymmetry_[%_l,r]_mean_pp" DOUBLE PRECISION,
    "TSpineRomR" DOUBLE PRECISION,
    "TSpineRomL" DOUBLE PRECISION,
    "ShoulderERL" DOUBLE PRECISION,
    "ShoulderERR" DOUBLE PRECISION,
    "ShoulderIRL" DOUBLE PRECISION,
    "ShoulderIRR" DOUBLE PRECISION,
    "pitching_session_date" TIMESTAMP(3),
    "pitch_speed_mph" DOUBLE PRECISION,
    "pitching_max_hss" DOUBLE PRECISION,
    "hitting_session_date" TIMESTAMP(3),
    "bat_speed_mph" DOUBLE PRECISION,
    "hitting_max_hss" DOUBLE PRECISION,
    "relative_strength" DOUBLE PRECISION,
    "body_weight_[lbs]" DOUBLE PRECISION,
    "athlete_uid" TEXT,

    CONSTRAINT "HpObp_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "HpObp_playing_level_idx" ON "public"."HpObp"("playing_level");

-- CreateIndex
CREATE INDEX "HpObp_athlete_uid_idx" ON "public"."HpObp"("athlete_uid");
